name: Build documentation

on:
  push

jobs:
  create_html:
    runs-on: ubuntu-latest

    steps:
    - name: Build Sphinx docs
    - uses: actions/checkout@v2
    - run: |
        cd ./docs
        make html
